### ISSUE TITLE
v12 compatability

### ISSUE THREAD

**Issue by ditzer252** [orangebutblue/Foundry-Login-Notification#2]
I've just upgraded Foundry to v12 and it seems that the log file structure has changed.
Do you have plans to update the watchdog?  Thanks.

**Comment by orangebutblue** [comment]
Yes, however, I'm still using v11 myself, so I don't have access to the new log files.

If you don't mind, could you upload one of your v12 log files for me, so I can take a look?

**Comment by ditzer252** [comment]
It seems like the log file structure is about the same, but a new, separate log file is generated each day.

**Comment by orangebutblue** [comment]
Thank you. You should definitely delete the log file, since it contains some IP addresses :-)

I've just pushed a change that I think should fix this. But obviously I couldn't test it on my machine. Let me know if it works for you!

**Comment by ditzer252** [comment]
works!  Thank you!
